// Vue/base/00-todo(3ways)/todoVuex/src/components/AddTodo.vue
<template>
	<h1>Add Todo</h1>
	<input
		type="text"
		placeholder="new todo..."
		v-model="inputText">
	<button
		@click="addTodo(inputText)">
		Add Todo
	</button>
</template>

<script setup>
import { ref } from 'vue'
import { useStore } from 'vuex'

const store = useStore()
const inputText = ref()

const addTodo = (text) => {
	store.commit('addTodo', text)
	inputText.value = ''
}



</script>

<style scoped lang='scss'></style>

// React/Redux/08-redux-persist-ts/src/components/AddTodo.tsx
import { useState } from "react"
import { useDispatch } from "react-redux"
import { addNewTodo } from "../store/todoSlice"



const AddTodo = () => {

	const [value, setValue] = useState('')
	const dispatch = useDispatch()

	const addTodoHandler = () => {
		dispatch(addNewTodo(value))
		setValue('')
	}

	return (
		<div>
			<input
				type="text"
				placeholder="new todo"
				value={value}
				onChange={e => setValue(e.target.value)}
			/>
			<button onClick={addTodoHandler}>Add todo</button>
		</div>
	)
}

export default AddTodo
