// React/Redux/08-redux-persist-ts/src/components/AddTodo.tsx
import { useState } from "react"
import { useDispatch } from "react-redux"
import { addNewTodo } from "../store/todoSlice"



const AddTodo = () => {

	const [value, setValue] = useState('')
	const dispatch = useDispatch()

	const addTodoHandler = () => {
		dispatch(addNewTodo(value))
		setValue('')
	}

	return (
		<div>
			<input
				type="text"
				placeholder="new todo"
				value={value}
				onChange={e => setValue(e.target.value)}
			/>
			<button onClick={addTodoHandler}>Add todo</button>
		</div>
	)
}

export default AddTodo

// Vue/base/00-todo(3ways)/todoPinia/src/components/AddTodo.vue
<template>
	<input
		type="text"
		placeholder="enter the message"
		v-model="message">
	<button
		@click="addTodoHandler(message)">
		Add Todo
	</button>

</template>

<script setup lang='ts'>
import { ref } from 'vue';
import { useTodoStore } from '@/stotes/store';

const todoStore = useTodoStore()
const message = ref<string>('')

const addTodoHandler = (inputValue: string) => {
	todoStore.addTodo(inputValue)
	message.value = ''
}
</script>

<style scoped lang='scss'></style>
