// react/ReactProjects/02-app-todo-st-v2/src/components/Todos/TodoList.jsx
import Todo from './Todo'
import styles from './TodoList.module.scss'

export default function TodoList({ todos, deleteTodo, toggleTodo }) {
	if (!todos.length) {
		return <div>No tasks in todo list</div>
	}
	return (
		<ul className={styles.todoList}>
			{todos.map((todo) => {
				return (
					<Todo
						key={todo.id}
						todo={todo}
						deleteTodo={deleteTodo}
						toggleTodo={toggleTodo}
					/>)
			})}
		</ul>
	)
}

// Vue/base/00-todo(3ways)/todoPinia/src/components/TodoList.vue
<template>
	<h3>Todo List:</h3>
	<ul v-for="{ id, text, isComplete } in todoStore.todos" :key="id">
		<li>
			<button @click="todoStore.changeStatus(id)">{{ isComplete }}</button>
			<span>{{ text }}</span>
			<button @click="todoStore.deleteTodo(id)">delete</button>
		</li>
	</ul>
</template>

<script setup lang='ts'>
import { useTodoStore } from '@/stotes/store'

const todoStore = useTodoStore()

</script>

<style scoped lang='scss'></style>
