// Vue/base/04-todo/src/components/TodoList.vue
<template>
	<h2>Todo List:</h2>
	<ul>
		<TodoItem v-for="todo in store.todos" :key="todo.id" :text="todo.text" :completed="todo.completed" :id="todo.id" />
	</ul>
</template>

<script>
import { store } from '../store.js';
import TodoItem from './TodoItem.vue'

export default {
	components: {
		TodoItem
	},
	data() {
		return {
			store
		}
	}
}
</script>

// React/ReactTypeScript/03-reduxTS/src/components/TodoList.tsx
import { useAppSelector } from '../hooks'
import TodoItem from './TodoItem'


const TodoList: React.FC = () => {

	const todos = useAppSelector(state => state.todos.list)

	return (
		<ul>
			{todos.map(todo => (
				<TodoItem
					key={todo.id}
					{...todo}
				/>
			))}
		</ul>
	)
}

export default TodoList
