// React/ReactTypeScript/04-reduxTsAsync/src/components/AddTodo.tsx
import { useState } from "react"
import { useAppDispatch } from "../hook";
import { addNewTodo } from "../store/todoSlice";


const AddTodo: React.FC = () => {

	const [inputValue, setInputValue] = useState('')
	const dispatch = useAppDispatch()

	const addTodoHandler = () => {
		dispatch(addNewTodo(inputValue))
		setInputValue('')
	}


	return (
		<div>
			<input
				type="text"
				placeholder="new Todo"
				value={inputValue}
				onChange={(e) => setInputValue(e.target.value)}
			/>
			<button onClick={addTodoHandler}>Add Todo</button>
		</div>
	)
}

export default AddTodo

// Vue/base/04-todo-pinia/src/components/AddTodo.vue
<template>
	<h1>Todo App</h1>
	<div>
		<input v-model="counter.inputValue" type="text" placeholder="enter todo...">
		<button @click="counter.addTodo()">Add Todo</button>
	</div>
</template>

<script setup>
//import { store } from "@/stores/store";
import { useCounterStore } from "@/stores/counterStore";

const counter = useCounterStore()


</script>

<style></style>
