// React/Redux/05-getPosts-todos/getPosts-todosV1/src/Components/todo/TodoList.jsx
import { useSelector } from "react-redux";
import TodoItem from "./TodoItem";
import { allTodos } from "./todoSlice";



export default function TodoList() {

	const todos = useSelector(allTodos)


	return (
		<ul>
			{todos.map(todo => (
				<TodoItem key={todo.id} todo={todo} />
			))}
		</ul>
	)
}

// Vue/base/04-todo-pinia/src/components/TodoList.vue
<template>
	<ul>
		<TodoItem v-for="todo in counter.todos" :todo="todo" :key="todo.key" />
	</ul>
</template>

<script setup>
//import { store } from "@/stores/store";
import TodoItem from "./TodoItem.vue";
import { useCounterStore } from "@/stores/counterStore";

const counter = useCounterStore()

</script>

<style></style>
