// React/Redux/05-getPosts-todos/getPosts-todosV1/src/Components/todo/TodoItem.jsx
import { useDispatch } from 'react-redux'
import { changeStatus, deleteTodo } from './todoSlice'

export default function TodoItem({ todo }) {

	const dispatch = useDispatch()

	const toggleTodoHaandler = (id) => {
		dispatch(changeStatus(id))
	}



	return (
		<li className="todoItem">
			<button
				type='button'
				onClick={() => toggleTodoHaandler(todo.id)}>
				{todo.completed ? 'completed' : 'NO Completed'}
			</button>
			<span>{todo.text}</span>
			<button onClick={() => dispatch(deleteTodo(todo.id))} >delete</button>
		</li>
	)
}

// Vue/base/04-todo-pinia/src/components/TodoItem.vue
<template>
	<li>
		<button @click="counter.deleteTodo(todo.id)">delete</button>
		<button @click="counter.toggleStatus(todo.id)">
			{{ todo.completed ? 'completed' : 'in process' }}
		</button>
		<span>{{ todo.text }}</span>
	</li>
</template>

<script setup>
import { useCounterStore } from "@/stores/counterStore";

const counter = useCounterStore()
defineProps({
	todo: Object
})
</script>

<style></style>
