// React/ReactTypeScript/03-reduxTS/src/components/TodoList.tsx
import { useAppSelector } from '../hooks'
import TodoItem from './TodoItem'


const TodoList: React.FC = () => {

	const todos = useAppSelector(state => state.todos.list)

	return (
		<ul>
			{todos.map(todo => (
				<TodoItem
					key={todo.id}
					{...todo}
				/>
			))}
		</ul>
	)
}

export default TodoList

// Vue/base/04-todo-pinia/src/components/TodoList.vue
<template>
	<ul>
		<TodoItem v-for="todo in counter.todos" :todo="todo" :key="todo.key" />
	</ul>
</template>

<script setup>
//import { store } from "@/stores/store";
import TodoItem from "./TodoItem.vue";
import { useCounterStore } from "@/stores/counterStore";

const counter = useCounterStore()

</script>

<style></style>
