// React/Router-Dom/02-React-Router-Dom/05-Search-Params/src/pages/About.jsx



export default function About() {
	return (
		<>
			<h1>About</h1>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt dignissimos, ullam eos velit exercitationem, aliquam inventore quidem modi voluptate reprehenderit eum consectetur nemo! Dolorem odio maiores necessitatibus, doloribus facere corrupti?</p>
		</>
	)
}

// Vue/base/11-router/src/views/About.vue
<template>
	<h1>About</h1>
	<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat fuga aut molestias eum, vitae eligendi enim
		repellendus eius velit natus impedit, quibusdam ad dolorem repudiandae rem aliquam officia nemo itaque.</p>
</template>

<script setup></script>

<style scoped></style>
