// React/Redux/07-redux-persist/src/components/todo/TodoItem.jsx
import { useDispatch } from "react-redux"
import { deleteTodo, toggleStatus } from "../../store/todoSlice"



const TodoItem = ({ todo }) => {

	const { text, id, completed } = todo

	const dispatch = useDispatch()

	return (
		<li>
			<button
				onClick={() => dispatch(toggleStatus(id))}
			>
				{completed ? 'true' : 'false'}
			</button>
			<span>{text}</span>
			<button
				onClick={() => dispatch(deleteTodo(id))}
			>
				delete
			</button>
		</li>
	)
}

export default TodoItem

// Vue/base/04-todo/src/components/TodoItem.vue
<template>
	<li>
		<button @click="store.toggleStatus(id)" :class="[completed ? 'todo done' : 'todo']">
			{{ completed ? 'done ' : 'processing' }}
		</button>
		<span>{{ text }}</span>
		<button @click="store.deleteTodo(id)">delete</button>
	</li>
</template>

<script>
import { store } from '../store.js';

export default {
	props: {
		text: {
			type: String
		},
		completed: {
			type: Boolean
		},
		id: {
			type: String
		}
	},
	data() {
		return {
			store
		}
	}
}
</script>


<style scoped lang="scss">
.todo {
	background-color: #fbbe00;
	display: inline-block;

	&.done {
		background-color: #55ac6e;
	}
}
</style>
