// Vue/base/04-todo/src/components/TodoList.vue
<template>
	<h2>Todo List:</h2>
	<ul>
		<TodoItem v-for="todo in store.todos" :key="todo.id" :text="todo.text" :completed="todo.completed" :id="todo.id" />
	</ul>
</template>

<script>
import { store } from '../store.js';
import TodoItem from './TodoItem.vue'

export default {
	components: {
		TodoItem
	},
	data() {
		return {
			store
		}
	}
}
</script>

// React/Redux/07-redux-persist/src/components/todo/TodoList.jsx
import { useSelector } from 'react-redux'
import TodoItem from './TodoItem'



const TodoList = () => {


	const todos = useSelector(state => state.todo.list)

	console.log(todos)

	return (
		<ul>
			{todos.map(todo => (
				<TodoItem key={todo.id} todo={todo} />
			))}
		</ul>
	)
}

export default TodoList
