// Vue/base/04-todo-pinia/src/components/TodoItem.vue
<template>
	<li>
		<button @click="counter.deleteTodo(todo.id)">delete</button>
		<button @click="counter.toggleStatus(todo.id)">
			{{ todo.completed ? 'completed' : 'in process' }}
		</button>
		<span>{{ todo.text }}</span>
	</li>
</template>

<script setup>
import { useCounterStore } from "@/stores/counterStore";

const counter = useCounterStore()
defineProps({
	todo: Object
})
</script>

<style></style>

// React/Redux/07-redux-persist/src/components/todo/TodoItem.jsx
import { useDispatch } from "react-redux"
import { deleteTodo, toggleStatus } from "../../store/todoSlice"



const TodoItem = ({ todo }) => {

	const { text, id, completed } = todo

	const dispatch = useDispatch()

	return (
		<li>
			<button
				onClick={() => dispatch(toggleStatus(id))}
			>
				{completed ? 'true' : 'false'}
			</button>
			<span>{text}</span>
			<button
				onClick={() => dispatch(deleteTodo(id))}
			>
				delete
			</button>
		</li>
	)
}

export default TodoItem
