// Vue/base/09-testVuex/src/components/Counter.vue
<template>
	<div>count: {{ store.state.count }}</div>
	<div>double count: {{ store.getters.double }}</div>
	<button
		@click="store.commit('increment', 500)">
		Increment
	</button>
	<button
		@click="decrement">
		decrement
	</button>
	<button @click="store.getters.double">double</button>
</template>

<script setup>
import { useStore } from 'vuex';

const store = useStore()

const decrement = () => {
	store.commit('decrement', 100)
}
</script>

<style scoped lang='scss'></style>

// React/Redux/01-start/src/Components/Counter.jsx
import { useSelector, useDispatch } from "react-redux"
import { increment, decrement } from "../store/counterSlice"


export default function Counter() {

	const count = useSelector((state) => state.counter.value)
	const dispatch = useDispatch()

	return (
		<>
			<button onClick={() => dispatch(increment())}>+++</button>
			<span>{count}</span>
			<button onClick={() => dispatch(decrement())}>---</button>
		</>
	)
}
