// Vue/base/00-todo(3ways)/todoPinia/src/components/AddTodo.vue
<template>
	<input
		type="text"
		placeholder="enter the message"
		v-model="message">
	<button
		@click="addTodoHandler(message)">
		Add Todo
	</button>

</template>

<script setup lang='ts'>
import { ref } from 'vue';
import { useTodoStore } from '@/stotes/store';

const todoStore = useTodoStore()
const message = ref<string>('')

const addTodoHandler = (inputValue: string) => {
	todoStore.addTodo(inputValue)
	message.value = ''
}
</script>

<style scoped lang='scss'></style>

// React/ReactTypeScript/04-reduxTsAsync/src/components/AddTodo.tsx
import { useState } from "react"
import { useAppDispatch } from "../hook";
import { addNewTodo } from "../store/todoSlice";


const AddTodo: React.FC = () => {

	const [inputValue, setInputValue] = useState('')
	const dispatch = useAppDispatch()

	const addTodoHandler = () => {
		dispatch(addNewTodo(inputValue))
		setInputValue('')
	}


	return (
		<div>
			<input
				type="text"
				placeholder="new Todo"
				value={inputValue}
				onChange={(e) => setInputValue(e.target.value)}
			/>
			<button onClick={addTodoHandler}>Add Todo</button>
		</div>
	)
}

export default AddTodo
