// Vue/base/04-todo-pinia/src/components/TodoItem.vue
<template>
	<li>
		<button @click="counter.deleteTodo(todo.id)">delete</button>
		<button @click="counter.toggleStatus(todo.id)">
			{{ todo.completed ? 'completed' : 'in process' }}
		</button>
		<span>{{ todo.text }}</span>
	</li>
</template>

<script setup>
import { useCounterStore } from "@/stores/counterStore";

const counter = useCounterStore()
defineProps({
	todo: Object
})
</script>

<style></style>

// React/ReactTypeScript/04-reduxTsAsync/src/components/TodoItem.tsx
import { toggleStatus, deleteTodo } from "../store/todoSlice";
import { useAppDispatch } from "../hook";

interface ITodoItemsProps {
	id: string,
	completed: boolean,
	title: string
}

const Todo: React.FC<ITodoItemsProps> = ({ title, id, completed }) => {

	const dispatch = useAppDispatch()


	return (
		<li>
			<button
				onClick={() => dispatch(toggleStatus(id))}
			>
				{completed ? 'complete' : 'in Process...'}
			</button>
			<span>{title}</span>
			<button
				onClick={() => dispatch(deleteTodo(id))}
			>
				delete
			</button>
		</li>
	)
}

export default Todo
